from arcade_imgui_demo import App


app = App()

app.use('index')
app.use('bullet')
app.use('button')
app.use('checkbox')
app.use('child')
app.use('circle')
app.use('cloud')
app.use('collapsingheader')
app.use('coloredit')
app.use('colors')
app.use('columns')
app.use('combo')
app.use('demo')
app.use('dnd')
app.use('dragfloat')
app.use('dummy')
app.use('fireworks')
app.use('font')
app.use('fontimage')
app.use('group')
app.use('image')
app.use('imagebutton')
app.use('imagedraw')
app.use('indent')
app.use('input')
app.use('line')
app.use('listbox')
app.use('mainmenu')
app.use('overlay')
app.use('popup')
app.use('rect')
app.use('ship')
app.use('sparks')
app.use('sprite')
app.use('text')
app.use('tooltip')
app.use('windowdraw')
app.use('windowmenu')

app.show('sparks')

app.run()
